/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.crud.gradebook.sagarw40.netbeans.client;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.WebResource;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.ws.rs.core.MediaType;
import model.GradeBook_CRUD_cl;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.map.SerializationConfig;

/**
 *
 * @author NAME
 */
public class gui extends javax.swing.JFrame {
    static int btnStep1 = 0;
//    private GradeBook_CRUD_cl clientObject;
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        jLayeredPane1.setVisible(false);
        jLayeredPane2.setVisible(false);
//        jTextArea1.addMouseListener(new ContextMenuMouseListener());
//        jTextArea1.setDragEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JRadioButton();
        btnGet = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JRadioButton();
        btnDelete = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelCreateOptn = new javax.swing.JPanel();
        btnCreateStudent = new javax.swing.JRadioButton();
        btnCreateWI = new javax.swing.JRadioButton();
        btnCreateTask = new javax.swing.JRadioButton();
        panelGetOptn = new javax.swing.JPanel();
        btnGetAll = new javax.swing.JRadioButton();
        btnGetStudent = new javax.swing.JRadioButton();
        btnGetWI = new javax.swing.JRadioButton();
        btnGetTask = new javax.swing.JRadioButton();
        btnGetGradebook = new javax.swing.JRadioButton();
        btnGetTaskNames = new javax.swing.JRadioButton();
        panelDeleteOptn = new javax.swing.JPanel();
        btnDeleteStudentTask = new javax.swing.JRadioButton();
        btnDeleteGradebookTask = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panelCreateStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        panelCreateWI = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        panelGetStudent = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        panelGetWI = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        panelUpdateStudent = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        panelDelete = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        panelCreateTask = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        panelGetTask = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        panelDeleteTask = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        statusCodeArea = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        uriArea = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Step1");

        buttonGroup1.add(btnCreate);
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnGet);
        btnGet.setText("Get");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnUpdate);
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDelete);
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnCreateStudent);
        btnCreateStudent.setText("Create a student entry");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnCreateWI);
        btnCreateWI.setText("Create a workItem for a student");
        btnCreateWI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWIActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnCreateTask);
        btnCreateTask.setText("Create a Task");
        btnCreateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateOptnLayout = new javax.swing.GroupLayout(panelCreateOptn);
        panelCreateOptn.setLayout(panelCreateOptnLayout);
        panelCreateOptnLayout.setHorizontalGroup(
            panelCreateOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateOptnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateStudent)
                    .addComponent(btnCreateTask)
                    .addComponent(btnCreateWI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreateOptnLayout.setVerticalGroup(
            panelCreateOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateOptnLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCreateStudent)
                .addGap(32, 32, 32)
                .addComponent(btnCreateTask)
                .addGap(30, 30, 30)
                .addComponent(btnCreateWI)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        buttonGroup3.add(btnGetAll);
        btnGetAll.setText("Get All students Name, ID");
        btnGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllActionPerformed(evt);
            }
        });

        buttonGroup3.add(btnGetStudent);
        btnGetStudent.setText("Get A student's info");
        btnGetStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStudentActionPerformed(evt);
            }
        });

        buttonGroup3.add(btnGetWI);
        btnGetWI.setText("Get a student's wi");
        btnGetWI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetWIActionPerformed(evt);
            }
        });

        buttonGroup3.add(btnGetTask);
        btnGetTask.setText("Get a task for all students");
        btnGetTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTaskActionPerformed(evt);
            }
        });

        buttonGroup3.add(btnGetGradebook);
        btnGetGradebook.setText("Get Gradebook");
        btnGetGradebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGradebookActionPerformed(evt);
            }
        });

        buttonGroup3.add(btnGetTaskNames);
        btnGetTaskNames.setText("Get Task Names in Gradebook");
        btnGetTaskNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTaskNamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGetOptnLayout = new javax.swing.GroupLayout(panelGetOptn);
        panelGetOptn.setLayout(panelGetOptnLayout);
        panelGetOptnLayout.setHorizontalGroup(
            panelGetOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetOptnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGetOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetTaskNames)
                    .addComponent(btnGetGradebook)
                    .addComponent(btnGetTask)
                    .addComponent(btnGetAll)
                    .addComponent(btnGetStudent)
                    .addComponent(btnGetWI))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelGetOptnLayout.setVerticalGroup(
            panelGetOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetOptnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnGetGradebook)
                .addGap(18, 18, 18)
                .addComponent(btnGetTaskNames)
                .addGap(18, 18, 18)
                .addComponent(btnGetTask)
                .addGap(18, 18, 18)
                .addComponent(btnGetAll)
                .addGap(18, 18, 18)
                .addComponent(btnGetStudent)
                .addGap(18, 18, 18)
                .addComponent(btnGetWI)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        buttonGroup4.add(btnDeleteStudentTask);
        btnDeleteStudentTask.setText("Delete a student's task");
        btnDeleteStudentTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentTaskActionPerformed(evt);
            }
        });

        buttonGroup4.add(btnDeleteGradebookTask);
        btnDeleteGradebookTask.setText("Delete a gradebook task");
        btnDeleteGradebookTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGradebookTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteOptnLayout = new javax.swing.GroupLayout(panelDeleteOptn);
        panelDeleteOptn.setLayout(panelDeleteOptnLayout);
        panelDeleteOptnLayout.setHorizontalGroup(
            panelDeleteOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteOptnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDeleteOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteGradebookTask)
                    .addComponent(btnDeleteStudentTask))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelDeleteOptnLayout.setVerticalGroup(
            panelDeleteOptnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteOptnLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnDeleteStudentTask)
                .addGap(41, 41, 41)
                .addComponent(btnDeleteGradebookTask)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(panelCreateOptn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelGetOptn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelDeleteOptn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCreateOptn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetOptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDeleteOptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCreateOptn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(panelGetOptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDeleteOptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Step2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate)
                            .addComponent(btnDelete)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGet)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1))))
        );

        jLabel1.setText("Enter Students info in JSON");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("name");

        javax.swing.GroupLayout panelCreateStudentLayout = new javax.swing.GroupLayout(panelCreateStudent);
        panelCreateStudent.setLayout(panelCreateStudentLayout);
        panelCreateStudentLayout.setHorizontalGroup(
            panelCreateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateStudentLayout.createSequentialGroup()
                .addGroup(panelCreateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreateStudentLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreateStudentLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1))
                    .addGroup(panelCreateStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCreateStudentLayout.setVerticalGroup(
            panelCreateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jLabel4.setText("ID");

        jLabel5.setText("assignment name");

        jLabel6.setText("Grade");

        jLabel7.setText("Feedback");

        jLabel8.setText("Percentage");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("NA");

        jTextField4.setText("-1");

        jTextField5.setText("-1");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateWILayout = new javax.swing.GroupLayout(panelCreateWI);
        panelCreateWI.setLayout(panelCreateWILayout);
        panelCreateWILayout.setHorizontalGroup(
            panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateWILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2))
                .addContainerGap())
            .addGroup(panelCreateWILayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreateWILayout.setVerticalGroup(
            panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateWILayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel9.setText("ID");

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGetStudentLayout = new javax.swing.GroupLayout(panelGetStudent);
        panelGetStudent.setLayout(panelGetStudentLayout);
        panelGetStudentLayout.setHorizontalGroup(
            panelGetStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetStudentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addGroup(panelGetStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelGetStudentLayout.setVerticalGroup(
            panelGetStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelGetStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(51, 51, 51))
        );

        jLabel10.setText("ID");

        jLabel11.setText("Assignment Name");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGetWILayout = new javax.swing.GroupLayout(panelGetWI);
        panelGetWI.setLayout(panelGetWILayout);
        panelGetWILayout.setHorizontalGroup(
            panelGetWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetWILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGetWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGetWILayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(panelGetWILayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8)))
                .addContainerGap())
            .addGroup(panelGetWILayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGetWILayout.setVerticalGroup(
            panelGetWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetWILayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelGetWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGetWILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(53, 53, 53))
        );

        jLabel12.setText("ID");

        jLabel13.setText("Assignment Name");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel14.setText("Grade");

        jLabel15.setText("Feedback");

        jLabel16.setText("Percentage");

        jTextField11.setText("-1");

        jTextField12.setText("NA");

        jTextField13.setText("-1");

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateStudentLayout = new javax.swing.GroupLayout(panelUpdateStudent);
        panelUpdateStudent.setLayout(panelUpdateStudentLayout);
        panelUpdateStudentLayout.setHorizontalGroup(
            panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateStudentLayout.createSequentialGroup()
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField13)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTextField11)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10)))
                    .addGroup(panelUpdateStudentLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateStudentLayout.setVerticalGroup(
            panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateStudentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel17.setText("ID");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jLabel18.setText("Assignment Name");

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTextField15)))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(55, 55, 55))
        );

        jLabel23.setText("Task Name");

        jButton7.setText("Submit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateTaskLayout = new javax.swing.GroupLayout(panelCreateTask);
        panelCreateTask.setLayout(panelCreateTaskLayout);
        panelCreateTaskLayout.setHorizontalGroup(
            panelCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jTextField16)
                .addContainerGap())
            .addGroup(panelCreateTaskLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton7)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelCreateTaskLayout.setVerticalGroup(
            panelCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateTaskLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(41, 41, 41))
        );

        jLabel24.setText("Task Name");

        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGetTaskLayout = new javax.swing.GroupLayout(panelGetTask);
        panelGetTask.setLayout(panelGetTaskLayout);
        panelGetTaskLayout.setHorizontalGroup(
            panelGetTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField17)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGetTaskLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(56, 56, 56))
        );
        panelGetTaskLayout.setVerticalGroup(
            panelGetTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetTaskLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelGetTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(41, 41, 41))
        );

        jLabel25.setText("Task Name");

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteTaskLayout = new javax.swing.GroupLayout(panelDeleteTask);
        panelDeleteTask.setLayout(panelDeleteTaskLayout);
        panelDeleteTaskLayout.setHorizontalGroup(
            panelDeleteTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField19)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteTaskLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(57, 57, 57))
        );
        panelDeleteTaskLayout.setVerticalGroup(
            panelDeleteTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteTaskLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelDeleteTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(34, 34, 34))
        );

        jLayeredPane2.setLayer(panelCreateStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelCreateWI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelGetStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelGetWI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelUpdateStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelCreateTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelGetTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panelDeleteTask, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCreateWI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCreateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetWI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCreateTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDeleteTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCreateWI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCreateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetWI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCreateTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGetTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDeleteTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2))
        );

        jLabel19.setText("HTTP Info + Output");

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        jLabel20.setText("HTTP Status Code");

        jLabel21.setText("URI");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(245, 245, 245)
                            .addComponent(jLabel19))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(statusCodeArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(uriArea))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(statusCodeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(uriArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
        if(btnCreateStudent.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateTask.setVisible(false);
            panelCreateStudent.setVisible(true);
            panelCreateWI.setVisible(false);
            panelGetTask.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else{
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(btnUpdate.isSelected()){
            
                jLayeredPane1.setVisible(false);
                jLayeredPane2.setVisible(true);
                panelCreateStudent.setVisible(false);
                panelCreateWI.setVisible(false);
                panelGetStudent.setVisible(false);
                panelGetWI.setVisible(false);
                panelUpdateStudent.setVisible(true);
                panelDelete.setVisible(false);
                panelCreateTask.setVisible(false);
                panelGetTask.setVisible(false);
                panelDeleteTask.setVisible(false);
            
        }
        else{
            
            jLayeredPane1.setVisible(false);
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(btnCreate.isSelected()){
            
                jLayeredPane1.setVisible(true);
                panelCreateOptn.setVisible(true);
                panelGetOptn.setVisible(false);
                panelDeleteOptn.setVisible(false);
                jLayeredPane2.setVisible(false);
            
        }
        else{
            
            jLayeredPane1.setVisible(false);
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        // TODO add your handling code here:
        if(btnGet.isSelected()){
            
                jLayeredPane1.setVisible(true);
                panelGetOptn.setVisible(true);
                panelCreateOptn.setVisible(false);
                panelDeleteOptn.setVisible(false);
                jLayeredPane2.setVisible(false);
            
        }
        else{
            
            jLayeredPane1.setVisible(false);
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(btnDelete.isSelected()){
            
                jLayeredPane1.setVisible(true);
                jLayeredPane2.setVisible(false);
                panelCreateOptn.setVisible(false);
                panelGetOptn.setVisible(false);
                panelDeleteOptn.setVisible(true);
                
            
        }
        else{
            
            jLayeredPane1.setVisible(false);
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateWIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWIActionPerformed
        // TODO add your handling code here:
        if(btnCreateWI.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateTask.setVisible(false);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(true);
            panelGetTask.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else{
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnCreateWIActionPerformed

    private void btnGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllActionPerformed
        // TODO add your handling code here:
        if(btnGetAll.isSelected()){
            try{
                ClientResponse response = getAllStudents();
                outputTextArea.setText(response.getEntity(String.class));
                statusCodeArea.setText(Integer.toString(response.getStatus()));
                uriArea.setText("");
            }
            catch(Exception e){
                outputTextArea.setText("No students in gradebook yet!");
                statusCodeArea.setText("204");
                uriArea.setText("");
            }
        }
        
    }//GEN-LAST:event_btnGetAllActionPerformed

    private void btnGetStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStudentActionPerformed
        // TODO add your handling code here:
        if(btnGetStudent.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateTask.setVisible(false);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetTask.setVisible(false);
            panelGetStudent.setVisible(true);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else{
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnGetStudentActionPerformed

    private void btnGetWIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetWIActionPerformed
        // TODO add your handling code here:
        if(btnGetWI.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateTask.setVisible(false);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetTask.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(true);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else{
            jLayeredPane2.setVisible(false);
        }
    }//GEN-LAST:event_btnGetWIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String input;
        ClientResponse response = createStudent(jTextField18.getText());
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        outputTextArea.setText(response.getEntity(String.class));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String input;
        input = "{ \"grade\" : "+jTextField4.getText() + ", \"feedback\" : \""+jTextField3.getText()+"\", \"percentage\" : "+jTextField5.getText()+"}";
        System.out.println(input);
        ClientResponse response = createWI(jTextField1.getText(), jTextField2.getText(), input);
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ClientResponse response = getStudent(jTextField6.getText());
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ClientResponse response = getWI(jTextField7.getText(),jTextField8.getText());
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String input;
        input = "{ \"grade\" : "+jTextField11.getText() + ", \"feedback\" : \""+jTextField12.getText()+"\", \"percentage\" : "+jTextField13.getText()+"}";
        System.out.println(input);
        ClientResponse response = updateStudent(jTextField9.getText(), jTextField10.getText(), input);
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        ClientResponse response = deleteWI(jTextField14.getText(),jTextField15.getText());
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ClientResponse response = createTask(jTextField16.getText());
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
            uriArea.setText(response.getLocation().toString());
        else 
            uriArea.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCreateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskActionPerformed
        // TODO add your handling code here:
        if(btnCreateTask.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateTask.setVisible(true);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetTask.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else
            jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_btnCreateTaskActionPerformed

    private void btnGetGradebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGradebookActionPerformed
        // TODO add your handling code here:
        if(btnGetGradebook.isSelected()){
            ClientResponse response = getGradebook();
            outputTextArea.setText(response.getEntity(String.class));
            statusCodeArea.setText(Integer.toString(response.getStatus()));
            if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
                uriArea.setText(response.getLocation().toString());
            else 
                uriArea.setText("");
        }
    }//GEN-LAST:event_btnGetGradebookActionPerformed

    private void btnGetTaskNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTaskNamesActionPerformed
        // TODO add your handling code here:
        if(btnGetTaskNames.isSelected()){
            ClientResponse response = getTaskNames();
            outputTextArea.setText(response.getEntity(String.class));
            statusCodeArea.setText(Integer.toString(response.getStatus()));
            if(!response.getLocation().toString().equals("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/"))
                uriArea.setText(response.getLocation().toString());
            else 
                uriArea.setText("");
        }
    }//GEN-LAST:event_btnGetTaskNamesActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(btnGetTask.isSelected()){
            ClientResponse response = getTask(jTextField17.getText());
            outputTextArea.setText(response.getEntity(String.class));
            statusCodeArea.setText(Integer.toString(response.getStatus()));
            uriArea.setText("");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnGetTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTaskActionPerformed
        // TODO add your handling code here:
        if(btnGetTask.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteTask.setVisible(false);
            panelCreateTask.setVisible(false);
            panelGetTask.setVisible(true);
        }
        else jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_btnGetTaskActionPerformed

    private void btnDeleteStudentTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentTaskActionPerformed
        // TODO add your handling code here:
        if(btnDeleteStudentTask.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(true);
            panelCreateTask.setVisible(false);
            panelGetTask.setVisible(false);
            panelDeleteTask.setVisible(false);
        }
        else jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_btnDeleteStudentTaskActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ClientResponse response = deleteTask(jTextField19.getText());
        outputTextArea.setText(response.getEntity(String.class));
        statusCodeArea.setText(Integer.toString(response.getStatus()));
        uriArea.setText(" ");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnDeleteGradebookTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGradebookTaskActionPerformed
        // TODO add your handling code here:
        if(btnDeleteGradebookTask.isSelected()){
            jLayeredPane2.setVisible(true);
            panelCreateStudent.setVisible(false);
            panelCreateWI.setVisible(false);
            panelGetStudent.setVisible(false);
            panelGetWI.setVisible(false);
            panelUpdateStudent.setVisible(false);
            panelDelete.setVisible(false);
            panelCreateTask.setVisible(false);
            panelGetTask.setVisible(false);
            panelDeleteTask.setVisible(true);
        }
        else jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_btnDeleteGradebookTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCreate;
    private javax.swing.JRadioButton btnCreateStudent;
    private javax.swing.JRadioButton btnCreateTask;
    private javax.swing.JRadioButton btnCreateWI;
    private javax.swing.JRadioButton btnDelete;
    private javax.swing.JRadioButton btnDeleteGradebookTask;
    private javax.swing.JRadioButton btnDeleteStudentTask;
    private javax.swing.JRadioButton btnGet;
    private javax.swing.JRadioButton btnGetAll;
    private javax.swing.JRadioButton btnGetGradebook;
    private javax.swing.JRadioButton btnGetStudent;
    private javax.swing.JRadioButton btnGetTask;
    private javax.swing.JRadioButton btnGetTaskNames;
    private javax.swing.JRadioButton btnGetWI;
    private javax.swing.JRadioButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JPanel panelCreateOptn;
    private javax.swing.JPanel panelCreateStudent;
    private javax.swing.JPanel panelCreateTask;
    private javax.swing.JPanel panelCreateWI;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelDeleteOptn;
    private javax.swing.JPanel panelDeleteTask;
    private javax.swing.JPanel panelGetOptn;
    private javax.swing.JPanel panelGetStudent;
    private javax.swing.JPanel panelGetTask;
    private javax.swing.JPanel panelGetWI;
    private javax.swing.JPanel panelUpdateStudent;
    private javax.swing.JTextField statusCodeArea;
    private javax.swing.JTextField uriArea;
    // End of variables declaration//GEN-END:variables
    
    private ClientResponse createStudent(String input){
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+input);
        return webResource2.accept("text/plain").post(ClientResponse.class);
//        try {
//                URL url = new URL("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students");
//                HttpURLConnection conn = (HttpURLConnection) url.openConnection();
//		conn.setDoOutput(true);
//		conn.setRequestMethod("POST");
//		conn.setRequestProperty("Content-Type", "application/json");
//
//
//                OutputStream os = conn.getOutputStream();
//                os.write(input.getBytes());
//		os.flush();
//
//                BufferedReader br = new BufferedReader(new InputStreamReader((conn.getInputStream())));
//
//		String output;
//		System.out.println("Output from Server! .... \n");
//		while ((output = br.readLine()) != null) {
//                    System.out.println(output);
//                    returnOutput = returnOutput.concat(output);
//		}
//                
//                ObjectMapper mapper = new ObjectMapper();
//                returnOutput= mapper.writerWithDefaultPrettyPrinter().writeValueAsString(returnOutput);
//                
//                System.out.println("Return Output : "+returnOutput);
//		conn.disconnect();
//
//        } catch (MalformedURLException e) {
//
//                e.printStackTrace();
//        } catch (IOException e) {
//
//                e.printStackTrace();
//
//        }
//        return returnOutput;
    }

    private ClientResponse createWI(String paramId, String paramAssignment, String input) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+paramId+"/"+paramAssignment);
        return webResource2.type(MediaType.APPLICATION_JSON).post(ClientResponse.class,input);
        
    }

    private ClientResponse getStudent(String paramId) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+paramId);
        return webResource2.type(MediaType.APPLICATION_JSON).get(ClientResponse.class);
    }

    private ClientResponse getWI(String paramId, String paramAssignment) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+paramId+"/"+paramAssignment);
        return webResource2.type(MediaType.APPLICATION_JSON).get(ClientResponse.class);
    }

    private ClientResponse updateStudent(String paramId, String paramAssignment, String input) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+paramId+"/"+paramAssignment);
        return webResource2.type(MediaType.APPLICATION_JSON).put(ClientResponse.class,input);
    }

    private ClientResponse deleteWI(String paramId, String paramAssignment) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students/"+paramId+"/"+paramAssignment);
        return webResource2.type(MediaType.APPLICATION_JSON).delete(ClientResponse.class);
    }

    private ClientResponse getAllStudents() {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Students");
        return webResource2.accept("text/plain").get(ClientResponse.class);

    }

    private ClientResponse createTask(String text) {
        String returnOutput =" ";
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Tasks/"+text);
        return webResource2.accept("text/plain").post(ClientResponse.class);
    }

    private ClientResponse getGradebook() {
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook");
        return webResource2.accept("application/json").get(ClientResponse.class);
    }

    private ClientResponse getTaskNames() {
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Tasks");
        return webResource2.accept("text/plain").get(ClientResponse.class);
    }

    private ClientResponse getTask(String input) {
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Tasks/"+input);
        return webResource2.accept("text/plain").get(ClientResponse.class);
    }

    private ClientResponse deleteTask(String text) {
        Client client = Client.create();
        WebResource webResource2 = client.resource("http://localhost:8080/CRUD-GradeBook-sagarw40-Netbeans/webresources/GradeBook/Tasks/"+text);
        return webResource2.accept("text/plain").delete(ClientResponse.class);
    }
}
